# License
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#logoFile="todo.png"
authors="Lemon_Juiced & TechDahTurtle"
description='''
Antiquity is a Minecraft mod for 26.2 that adds a variety of new features based on the historical Antiquity period.
'''

# Dependencies
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="terrablender"
    type="required"
    versionRange="[26.2.0.0.0,)"
    ordering="NONE"
    side="BOTH"